---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exclusive-pvc-failure
  annotations:
    volume.beta.kubernetes.io/storage-class: pre-populated  # should use StorageClass for 1.6 and later
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      genericLabel: incorrectvalue
---
apiVersion: v1
kind: Pod
metadata:
  name: exclusive-pvc-failure
  labels:
    failure-domain.beta.kubernetes.io/zone: us-east-1b  # AWS limitation, can't mount between zones
    app: exclusive-pvc-failure
spec:
  containers:
    - name: sample-go
      image: quay.io/samsung_cnct/example-k8s-storage:0.2
      ports:
      - containerPort: 8080
      volumeMounts:
        - name: exclusive-pvc-failure
          mountPath: /mnt/pv
  volumes:
    - name: exclusive-pvc-failure
      persistentVolumeClaim:
        claimName: exclusive-pvc-failure