kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: pre-populated
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sc-example
  annotations:
    volume.beta.kubernetes.io/storage-class: pre-populated  # should use StorageClass for 1.6 and later
  labels:
    genericLabel: value
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-04ea4ceaa2c1e1c12
    fsType: ext4  # k8s will format the drive (if mkfs is available for that fs on the node)